name: Validation OHRI CI

on:
  push: 
    branches:
      - microfrontends

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Print Secret Values 
        run: |
          echo " NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }} "
          echo " host: ${{ secrets.HISTAC_HOST }} "
          echo " username: ${{ secrets.HISTAC_USERNAME }} "
          echo " privateKey: ${{ secrets.HISTAC_KEY}}"
          echo " port: ${{ secrets.HISTAC_PORT }} "
          echo " DEV NAMIBIA "
          echo " port: ${{ secrets.HISTAC_NAMIBIA_PORT }} "
          echo " host: ${{ secrets.HISTAC_DEV_NAMIBIA_HOST }} "
          echo "  port: ${{ secrets.HISTAC_DEV_NAMIBIA_PORT }}"
          echo "  "
          echo "  " 
          echo "  "
          echo "  "   